data_ingestion:
  raw_data_path: "data/weatherHistory.csv"
  preprocessed_data_path: "artifacts/preprocessed.csv"
  test_size: 0.2
  random_state: 42

data_preprocessing:
  drop_columns: ["Formatted Date", "Daily Summary", "Loud Cover"]
  numerical_columns: 
    - "Temperature (C)"
    - "Apparent Temperature (C)"
    - "Humidity"
    - "Wind Speed (km/h)"
    - "Wind Bearing (degrees)"
    - "Visibility (km)"
    - "Pressure (millibars)"
  categorical_columns: ["Summary", "Precip Type"]

model:
  algorithm: "RandomForestClassifier"
  n_estimators: 100
  random_state: 42
  target_column: "Precip Type"

training:
  batch_size: 32
  epochs: 10

artifacts:
  model_path: "artifacts/random_forest_model.pkl"
  metrics_path: "artifacts/metrics.json"
