name: MLOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Training
        run: python src/components/training.py

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: artifacts/random_forest_model.pkl
