name: MLOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  upload-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Skip training in CI/CD - Assume model is already trained locally

      - name: Upload Model to S3
        run: python src/cloud/s3_connection.py

      - name: Confirm Upload
        run: echo "✅ Model uploaded to S3 successfully!"
